---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Get path
  shell: |
    echo "pwd"
    pwd

- name: Copy backend page
  copy:
    src: "/root/project/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"
    backup: yes

- name: Unzip
  shell: |
    cd ~/web
    tar -xzf artifact.tar.gz
    pwd
    ls -la

- name: Install docker
  shell: |
    cd ~/web
    chmod +x install_docker.sh 
    ./install_docker.sh

- name: Install minikube
  shell: |
    cd ~/web
    chmod +x install_minikube.sh 
    ./install_minikube.sh

- name: Install kubectl
  shell: |
    cd ~/web
    chmod +x install_kubectl.sh 
    ./install_kubectl.sh

- name: Start minikube
  shell: |
    minikube start --force
    kubectl get nodes

